import type { FilterLabels } from "@/components/reui/filters/filters-types";

export const toolbarFilterLabels: Partial<FilterLabels> = {
  actionsLabel: "操作",
  addCondition: "添加筛选",
  addFilter: "添加筛选",
  and: "并且",
  apply: "应用",
  back: "返回",
  branchAffordance: "展开选项",
  chipMenu: (label) => `${label}筛选选项`,
  clear: "清空",
  clearAll: "清空筛选",
  countAnnouncement: (count) => `当前 ${count} 个筛选条件`,
  discard: "取消",
  empty: "没有匹配项",
  error: "加载失败",
  exclusiveAnnouncement: (label, count) => `已选择${label}，清除其他 ${count} 项`,
  exclusiveHint: "不能与其他选项同时选择",
  fieldsLabel: "筛选字段",
  filterLabel: (condition) => condition,
  filtersLabel: "筛选条件（同时满足）",
  incomplete: "未完成的筛选",
  issueOperator: "请选择条件",
  issueRange: "请选择起止日期",
  issueRangeOrder: "结束日期不能早于开始日期",
  issueValue: "请选择筛选值",
  itemCount: (count) => `${count} 项`,
  loadMore: "加载更多",
  loading: "加载中…",
  loadingMore: "加载更多…",
  noValue: "未选择",
  pathSeparator: " / ",
  rangeFrom: (label) => `${label}起始值`,
  rangeSeparator: "至",
  rangeTo: (label) => `${label}结束值`,
  readOnly: "此筛选不可修改",
  remove: "移除筛选",
  resultsAnnouncement: (count) => `${count} 个结果`,
  retry: "重试",
  searchFields: "搜索筛选字段…",
  searchOperators: "搜索条件…",
  searchOptions: "搜索选项…",
  selectCondition: "选择条件",
  selectPlaceholder: "选择…",
  stepAnnouncement: (_step, label) => `选择${label}`,
  valueCount: (count) => `已选 ${count} 项`,
  valueDetail: (summary, values) => `${summary}：${values.join("、")}`,
  valuePlaceholder: "输入…",
  valueRange: (from, to) => `${from} 至 ${to}`,
};
