/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectWorkspaceRouteImport } from './routes/select-workspace'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WSlugRouteImport } from './routes/w.$slug'
import { Route as StudioResumesRouteImport } from './routes/studio.resumes'
import { Route as StudioResumePoolRouteImport } from './routes/studio.resume-pool'
import { Route as StudioInterviewsRouteImport } from './routes/studio.interviews'
import { Route as RRoundIdRouteImport } from './routes/r.$roundId'
import { Route as PlatformUsersRouteImport } from './routes/platform.users'
import { Route as PlatformQueuesRouteImport } from './routes/platform.queues'
import { Route as PlatformOrganizationsRouteImport } from './routes/platform.organizations'
import { Route as PlatformMailIngestAccountsRouteImport } from './routes/platform.mail-ingest-accounts'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as InterviewIdRouteImport } from './routes/interview.$id'
import { Route as HumanInterviewInviteTokenRouteImport } from './routes/human-interview.$inviteToken'
import { Route as WSlugStudioRouteImport } from './routes/w.$slug.studio'
import { Route as WSlugChatRouteImport } from './routes/w.$slug.chat'
import { Route as InterviewIdRoundIdRouteImport } from './routes/interview.$id.$roundId'
import { Route as HumanInterviewInterviewerInviteTokenRouteImport } from './routes/human-interview.interviewer.$inviteToken'
import { Route as WSlugChatIndexRouteImport } from './routes/w.$slug.chat.index'
import { Route as WSlugStudioResumesRouteImport } from './routes/w.$slug.studio.resumes'
import { Route as WSlugStudioResumePoolRouteImport } from './routes/w.$slug.studio.resume-pool'
import { Route as WSlugStudioMembersRouteImport } from './routes/w.$slug.studio.members'
import { Route as WSlugStudioMeRouteImport } from './routes/w.$slug.studio.me'
import { Route as WSlugStudioMailIngestAccountsRouteImport } from './routes/w.$slug.studio.mail-ingest-accounts'
import { Route as WSlugStudioJobDescriptionsRouteImport } from './routes/w.$slug.studio.job-descriptions'
import { Route as WSlugStudioInterviewsRouteImport } from './routes/w.$slug.studio.interviews'
import { Route as WSlugStudioInterviewersRouteImport } from './routes/w.$slug.studio.interviewers'
import { Route as WSlugStudioInterviewQuestionsRouteImport } from './routes/w.$slug.studio.interview-questions'
import { Route as WSlugStudioGlobalConfigRouteImport } from './routes/w.$slug.studio.global-config'
import { Route as WSlugStudioFormsRouteImport } from './routes/w.$slug.studio.forms'
import { Route as WSlugStudioDepartmentsRouteImport } from './routes/w.$slug.studio.departments'
import { Route as WSlugStudioDashboardRouteImport } from './routes/w.$slug.studio.dashboard'
import { Route as WSlugChatSessionIdRouteImport } from './routes/w.$slug.chat.$sessionId'
import { Route as WSlugStudioInterviewsRoundIdRouteImport } from './routes/w.$slug.studio.interviews.$roundId'

const SelectWorkspaceRoute = SelectWorkspaceRouteImport.update({
  id: '/select-workspace',
  path: '/select-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WSlugRoute = WSlugRouteImport.update({
  id: '/w/$slug',
  path: '/w/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioResumesRoute = StudioResumesRouteImport.update({
  id: '/studio/resumes',
  path: '/studio/resumes',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioResumePoolRoute = StudioResumePoolRouteImport.update({
  id: '/studio/resume-pool',
  path: '/studio/resume-pool',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioInterviewsRoute = StudioInterviewsRouteImport.update({
  id: '/studio/interviews',
  path: '/studio/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RRoundIdRoute = RRoundIdRouteImport.update({
  id: '/r/$roundId',
  path: '/r/$roundId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformUsersRoute = PlatformUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformQueuesRoute = PlatformQueuesRouteImport.update({
  id: '/queues',
  path: '/queues',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformOrganizationsRoute = PlatformOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformMailIngestAccountsRoute =
  PlatformMailIngestAccountsRouteImport.update({
    id: '/mail-ingest-accounts',
    path: '/mail-ingest-accounts',
    getParentRoute: () => PlatformRoute,
  } as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewIdRoute = InterviewIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InterviewRoute,
} as any)
const HumanInterviewInviteTokenRoute =
  HumanInterviewInviteTokenRouteImport.update({
    id: '/human-interview/$inviteToken',
    path: '/human-interview/$inviteToken',
    getParentRoute: () => rootRouteImport,
  } as any)
const WSlugStudioRoute = WSlugStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugChatRoute = WSlugChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => WSlugRoute,
} as any)
const InterviewIdRoundIdRoute = InterviewIdRoundIdRouteImport.update({
  id: '/$roundId',
  path: '/$roundId',
  getParentRoute: () => InterviewIdRoute,
} as any)
const HumanInterviewInterviewerInviteTokenRoute =
  HumanInterviewInterviewerInviteTokenRouteImport.update({
    id: '/human-interview/interviewer/$inviteToken',
    path: '/human-interview/interviewer/$inviteToken',
    getParentRoute: () => rootRouteImport,
  } as any)
const WSlugChatIndexRoute = WSlugChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WSlugChatRoute,
} as any)
const WSlugStudioResumesRoute = WSlugStudioResumesRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => WSlugStudioRoute,
} as any)
const WSlugStudioResumePoolRoute = WSlugStudioResumePoolRouteImport.update({
  id: '/resume-pool',
  path: '/resume-pool',
  getParentRoute: () => WSlugStudioRoute,
} as any)
const WSlugStudioMembersRoute = WSlugStudioMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => WSlugStudioRoute,
} as any)
const WSlugStudioMeRoute = WSlugStudioMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => WSlugStudioRoute,
} as any)
const WSlugStudioMailIngestAccountsRoute =
  WSlugStudioMailIngestAccountsRouteImport.update({
    id: '/mail-ingest-accounts',
    path: '/mail-ingest-accounts',
    getParentRoute: () => WSlugStudioRoute,
  } as any)
const WSlugStudioJobDescriptionsRoute =
  WSlugStudioJobDescriptionsRouteImport.update({
    id: '/job-descriptions',
    path: '/job-descriptions',
    getParentRoute: () => WSlugStudioRoute,
  } as any)
const WSlugStudioInterviewsRoute = WSlugStudioInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => WSlugStudioRoute,
} as any)
const WSlugStudioInterviewersRoute = WSlugStudioInterviewersRouteImport.update({
  id: '/interviewers',
  path: '/interviewers',
  getParentRoute: () => WSlugStudioRoute,
} as any)
const WSlugStudioInterviewQuestionsRoute =
  WSlugStudioInterviewQuestionsRouteImport.update({
    id: '/interview-questions',
    path: '/interview-questions',
    getParentRoute: () => WSlugStudioRoute,
  } as any)
const WSlugStudioGlobalConfigRoute = WSlugStudioGlobalConfigRouteImport.update({
  id: '/global-config',
  path: '/global-config',
  getParentRoute: () => WSlugStudioRoute,
} as any)
const WSlugStudioFormsRoute = WSlugStudioFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => WSlugStudioRoute,
} as any)
const WSlugStudioDepartmentsRoute = WSlugStudioDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => WSlugStudioRoute,
} as any)
const WSlugStudioDashboardRoute = WSlugStudioDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WSlugStudioRoute,
} as any)
const WSlugChatSessionIdRoute = WSlugChatSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => WSlugChatRoute,
} as any)
const WSlugStudioInterviewsRoundIdRoute =
  WSlugStudioInterviewsRoundIdRouteImport.update({
    id: '/$roundId',
    path: '/$roundId',
    getParentRoute: () => WSlugStudioInterviewsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/interview': typeof InterviewRouteWithChildren
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRouteWithChildren
  '/select-workspace': typeof SelectWorkspaceRoute
  '/human-interview/$inviteToken': typeof HumanInterviewInviteTokenRoute
  '/interview/$id': typeof InterviewIdRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/join/$code': typeof JoinCodeRoute
  '/platform/mail-ingest-accounts': typeof PlatformMailIngestAccountsRoute
  '/platform/organizations': typeof PlatformOrganizationsRoute
  '/platform/queues': typeof PlatformQueuesRoute
  '/platform/users': typeof PlatformUsersRoute
  '/r/$roundId': typeof RRoundIdRoute
  '/studio/interviews': typeof StudioInterviewsRoute
  '/studio/resume-pool': typeof StudioResumePoolRoute
  '/studio/resumes': typeof StudioResumesRoute
  '/w/$slug': typeof WSlugRouteWithChildren
  '/human-interview/interviewer/$inviteToken': typeof HumanInterviewInterviewerInviteTokenRoute
  '/interview/$id/$roundId': typeof InterviewIdRoundIdRoute
  '/w/$slug/chat': typeof WSlugChatRouteWithChildren
  '/w/$slug/studio': typeof WSlugStudioRouteWithChildren
  '/w/$slug/chat/$sessionId': typeof WSlugChatSessionIdRoute
  '/w/$slug/studio/dashboard': typeof WSlugStudioDashboardRoute
  '/w/$slug/studio/departments': typeof WSlugStudioDepartmentsRoute
  '/w/$slug/studio/forms': typeof WSlugStudioFormsRoute
  '/w/$slug/studio/global-config': typeof WSlugStudioGlobalConfigRoute
  '/w/$slug/studio/interview-questions': typeof WSlugStudioInterviewQuestionsRoute
  '/w/$slug/studio/interviewers': typeof WSlugStudioInterviewersRoute
  '/w/$slug/studio/interviews': typeof WSlugStudioInterviewsRouteWithChildren
  '/w/$slug/studio/job-descriptions': typeof WSlugStudioJobDescriptionsRoute
  '/w/$slug/studio/mail-ingest-accounts': typeof WSlugStudioMailIngestAccountsRoute
  '/w/$slug/studio/me': typeof WSlugStudioMeRoute
  '/w/$slug/studio/members': typeof WSlugStudioMembersRoute
  '/w/$slug/studio/resume-pool': typeof WSlugStudioResumePoolRoute
  '/w/$slug/studio/resumes': typeof WSlugStudioResumesRoute
  '/w/$slug/chat/': typeof WSlugChatIndexRoute
  '/w/$slug/studio/interviews/$roundId': typeof WSlugStudioInterviewsRoundIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/interview': typeof InterviewRouteWithChildren
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRouteWithChildren
  '/select-workspace': typeof SelectWorkspaceRoute
  '/human-interview/$inviteToken': typeof HumanInterviewInviteTokenRoute
  '/interview/$id': typeof InterviewIdRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/join/$code': typeof JoinCodeRoute
  '/platform/mail-ingest-accounts': typeof PlatformMailIngestAccountsRoute
  '/platform/organizations': typeof PlatformOrganizationsRoute
  '/platform/queues': typeof PlatformQueuesRoute
  '/platform/users': typeof PlatformUsersRoute
  '/r/$roundId': typeof RRoundIdRoute
  '/studio/interviews': typeof StudioInterviewsRoute
  '/studio/resume-pool': typeof StudioResumePoolRoute
  '/studio/resumes': typeof StudioResumesRoute
  '/w/$slug': typeof WSlugRouteWithChildren
  '/human-interview/interviewer/$inviteToken': typeof HumanInterviewInterviewerInviteTokenRoute
  '/interview/$id/$roundId': typeof InterviewIdRoundIdRoute
  '/w/$slug/studio': typeof WSlugStudioRouteWithChildren
  '/w/$slug/chat/$sessionId': typeof WSlugChatSessionIdRoute
  '/w/$slug/studio/dashboard': typeof WSlugStudioDashboardRoute
  '/w/$slug/studio/departments': typeof WSlugStudioDepartmentsRoute
  '/w/$slug/studio/forms': typeof WSlugStudioFormsRoute
  '/w/$slug/studio/global-config': typeof WSlugStudioGlobalConfigRoute
  '/w/$slug/studio/interview-questions': typeof WSlugStudioInterviewQuestionsRoute
  '/w/$slug/studio/interviewers': typeof WSlugStudioInterviewersRoute
  '/w/$slug/studio/interviews': typeof WSlugStudioInterviewsRouteWithChildren
  '/w/$slug/studio/job-descriptions': typeof WSlugStudioJobDescriptionsRoute
  '/w/$slug/studio/mail-ingest-accounts': typeof WSlugStudioMailIngestAccountsRoute
  '/w/$slug/studio/me': typeof WSlugStudioMeRoute
  '/w/$slug/studio/members': typeof WSlugStudioMembersRoute
  '/w/$slug/studio/resume-pool': typeof WSlugStudioResumePoolRoute
  '/w/$slug/studio/resumes': typeof WSlugStudioResumesRoute
  '/w/$slug/chat': typeof WSlugChatIndexRoute
  '/w/$slug/studio/interviews/$roundId': typeof WSlugStudioInterviewsRoundIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/interview': typeof InterviewRouteWithChildren
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRouteWithChildren
  '/select-workspace': typeof SelectWorkspaceRoute
  '/human-interview/$inviteToken': typeof HumanInterviewInviteTokenRoute
  '/interview/$id': typeof InterviewIdRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/join/$code': typeof JoinCodeRoute
  '/platform/mail-ingest-accounts': typeof PlatformMailIngestAccountsRoute
  '/platform/organizations': typeof PlatformOrganizationsRoute
  '/platform/queues': typeof PlatformQueuesRoute
  '/platform/users': typeof PlatformUsersRoute
  '/r/$roundId': typeof RRoundIdRoute
  '/studio/interviews': typeof StudioInterviewsRoute
  '/studio/resume-pool': typeof StudioResumePoolRoute
  '/studio/resumes': typeof StudioResumesRoute
  '/w/$slug': typeof WSlugRouteWithChildren
  '/human-interview/interviewer/$inviteToken': typeof HumanInterviewInterviewerInviteTokenRoute
  '/interview/$id/$roundId': typeof InterviewIdRoundIdRoute
  '/w/$slug/chat': typeof WSlugChatRouteWithChildren
  '/w/$slug/studio': typeof WSlugStudioRouteWithChildren
  '/w/$slug/chat/$sessionId': typeof WSlugChatSessionIdRoute
  '/w/$slug/studio/dashboard': typeof WSlugStudioDashboardRoute
  '/w/$slug/studio/departments': typeof WSlugStudioDepartmentsRoute
  '/w/$slug/studio/forms': typeof WSlugStudioFormsRoute
  '/w/$slug/studio/global-config': typeof WSlugStudioGlobalConfigRoute
  '/w/$slug/studio/interview-questions': typeof WSlugStudioInterviewQuestionsRoute
  '/w/$slug/studio/interviewers': typeof WSlugStudioInterviewersRoute
  '/w/$slug/studio/interviews': typeof WSlugStudioInterviewsRouteWithChildren
  '/w/$slug/studio/job-descriptions': typeof WSlugStudioJobDescriptionsRoute
  '/w/$slug/studio/mail-ingest-accounts': typeof WSlugStudioMailIngestAccountsRoute
  '/w/$slug/studio/me': typeof WSlugStudioMeRoute
  '/w/$slug/studio/members': typeof WSlugStudioMembersRoute
  '/w/$slug/studio/resume-pool': typeof WSlugStudioResumePoolRoute
  '/w/$slug/studio/resumes': typeof WSlugStudioResumesRoute
  '/w/$slug/chat/': typeof WSlugChatIndexRoute
  '/w/$slug/studio/interviews/$roundId': typeof WSlugStudioInterviewsRoundIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/interview'
    | '/login'
    | '/platform'
    | '/select-workspace'
    | '/human-interview/$inviteToken'
    | '/interview/$id'
    | '/invite/$token'
    | '/join/$code'
    | '/platform/mail-ingest-accounts'
    | '/platform/organizations'
    | '/platform/queues'
    | '/platform/users'
    | '/r/$roundId'
    | '/studio/interviews'
    | '/studio/resume-pool'
    | '/studio/resumes'
    | '/w/$slug'
    | '/human-interview/interviewer/$inviteToken'
    | '/interview/$id/$roundId'
    | '/w/$slug/chat'
    | '/w/$slug/studio'
    | '/w/$slug/chat/$sessionId'
    | '/w/$slug/studio/dashboard'
    | '/w/$slug/studio/departments'
    | '/w/$slug/studio/forms'
    | '/w/$slug/studio/global-config'
    | '/w/$slug/studio/interview-questions'
    | '/w/$slug/studio/interviewers'
    | '/w/$slug/studio/interviews'
    | '/w/$slug/studio/job-descriptions'
    | '/w/$slug/studio/mail-ingest-accounts'
    | '/w/$slug/studio/me'
    | '/w/$slug/studio/members'
    | '/w/$slug/studio/resume-pool'
    | '/w/$slug/studio/resumes'
    | '/w/$slug/chat/'
    | '/w/$slug/studio/interviews/$roundId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/interview'
    | '/login'
    | '/platform'
    | '/select-workspace'
    | '/human-interview/$inviteToken'
    | '/interview/$id'
    | '/invite/$token'
    | '/join/$code'
    | '/platform/mail-ingest-accounts'
    | '/platform/organizations'
    | '/platform/queues'
    | '/platform/users'
    | '/r/$roundId'
    | '/studio/interviews'
    | '/studio/resume-pool'
    | '/studio/resumes'
    | '/w/$slug'
    | '/human-interview/interviewer/$inviteToken'
    | '/interview/$id/$roundId'
    | '/w/$slug/studio'
    | '/w/$slug/chat/$sessionId'
    | '/w/$slug/studio/dashboard'
    | '/w/$slug/studio/departments'
    | '/w/$slug/studio/forms'
    | '/w/$slug/studio/global-config'
    | '/w/$slug/studio/interview-questions'
    | '/w/$slug/studio/interviewers'
    | '/w/$slug/studio/interviews'
    | '/w/$slug/studio/job-descriptions'
    | '/w/$slug/studio/mail-ingest-accounts'
    | '/w/$slug/studio/me'
    | '/w/$slug/studio/members'
    | '/w/$slug/studio/resume-pool'
    | '/w/$slug/studio/resumes'
    | '/w/$slug/chat'
    | '/w/$slug/studio/interviews/$roundId'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/interview'
    | '/login'
    | '/platform'
    | '/select-workspace'
    | '/human-interview/$inviteToken'
    | '/interview/$id'
    | '/invite/$token'
    | '/join/$code'
    | '/platform/mail-ingest-accounts'
    | '/platform/organizations'
    | '/platform/queues'
    | '/platform/users'
    | '/r/$roundId'
    | '/studio/interviews'
    | '/studio/resume-pool'
    | '/studio/resumes'
    | '/w/$slug'
    | '/human-interview/interviewer/$inviteToken'
    | '/interview/$id/$roundId'
    | '/w/$slug/chat'
    | '/w/$slug/studio'
    | '/w/$slug/chat/$sessionId'
    | '/w/$slug/studio/dashboard'
    | '/w/$slug/studio/departments'
    | '/w/$slug/studio/forms'
    | '/w/$slug/studio/global-config'
    | '/w/$slug/studio/interview-questions'
    | '/w/$slug/studio/interviewers'
    | '/w/$slug/studio/interviews'
    | '/w/$slug/studio/job-descriptions'
    | '/w/$slug/studio/mail-ingest-accounts'
    | '/w/$slug/studio/me'
    | '/w/$slug/studio/members'
    | '/w/$slug/studio/resume-pool'
    | '/w/$slug/studio/resumes'
    | '/w/$slug/chat/'
    | '/w/$slug/studio/interviews/$roundId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  InterviewRoute: typeof InterviewRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlatformRoute: typeof PlatformRouteWithChildren
  SelectWorkspaceRoute: typeof SelectWorkspaceRoute
  HumanInterviewInviteTokenRoute: typeof HumanInterviewInviteTokenRoute
  InviteTokenRoute: typeof InviteTokenRoute
  JoinCodeRoute: typeof JoinCodeRoute
  RRoundIdRoute: typeof RRoundIdRoute
  StudioInterviewsRoute: typeof StudioInterviewsRoute
  StudioResumePoolRoute: typeof StudioResumePoolRoute
  StudioResumesRoute: typeof StudioResumesRoute
  WSlugRoute: typeof WSlugRouteWithChildren
  HumanInterviewInterviewerInviteTokenRoute: typeof HumanInterviewInterviewerInviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-workspace': {
      id: '/select-workspace'
      path: '/select-workspace'
      fullPath: '/select-workspace'
      preLoaderRoute: typeof SelectWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$slug': {
      id: '/w/$slug'
      path: '/w/$slug'
      fullPath: '/w/$slug'
      preLoaderRoute: typeof WSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/resumes': {
      id: '/studio/resumes'
      path: '/studio/resumes'
      fullPath: '/studio/resumes'
      preLoaderRoute: typeof StudioResumesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/resume-pool': {
      id: '/studio/resume-pool'
      path: '/studio/resume-pool'
      fullPath: '/studio/resume-pool'
      preLoaderRoute: typeof StudioResumePoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/interviews': {
      id: '/studio/interviews'
      path: '/studio/interviews'
      fullPath: '/studio/interviews'
      preLoaderRoute: typeof StudioInterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$roundId': {
      id: '/r/$roundId'
      path: '/r/$roundId'
      fullPath: '/r/$roundId'
      preLoaderRoute: typeof RRoundIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/users': {
      id: '/platform/users'
      path: '/users'
      fullPath: '/platform/users'
      preLoaderRoute: typeof PlatformUsersRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/queues': {
      id: '/platform/queues'
      path: '/queues'
      fullPath: '/platform/queues'
      preLoaderRoute: typeof PlatformQueuesRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/organizations': {
      id: '/platform/organizations'
      path: '/organizations'
      fullPath: '/platform/organizations'
      preLoaderRoute: typeof PlatformOrganizationsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/mail-ingest-accounts': {
      id: '/platform/mail-ingest-accounts'
      path: '/mail-ingest-accounts'
      fullPath: '/platform/mail-ingest-accounts'
      preLoaderRoute: typeof PlatformMailIngestAccountsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/$id': {
      id: '/interview/$id'
      path: '/$id'
      fullPath: '/interview/$id'
      preLoaderRoute: typeof InterviewIdRouteImport
      parentRoute: typeof InterviewRoute
    }
    '/human-interview/$inviteToken': {
      id: '/human-interview/$inviteToken'
      path: '/human-interview/$inviteToken'
      fullPath: '/human-interview/$inviteToken'
      preLoaderRoute: typeof HumanInterviewInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$slug/studio': {
      id: '/w/$slug/studio'
      path: '/studio'
      fullPath: '/w/$slug/studio'
      preLoaderRoute: typeof WSlugStudioRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/chat': {
      id: '/w/$slug/chat'
      path: '/chat'
      fullPath: '/w/$slug/chat'
      preLoaderRoute: typeof WSlugChatRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/interview/$id/$roundId': {
      id: '/interview/$id/$roundId'
      path: '/$roundId'
      fullPath: '/interview/$id/$roundId'
      preLoaderRoute: typeof InterviewIdRoundIdRouteImport
      parentRoute: typeof InterviewIdRoute
    }
    '/human-interview/interviewer/$inviteToken': {
      id: '/human-interview/interviewer/$inviteToken'
      path: '/human-interview/interviewer/$inviteToken'
      fullPath: '/human-interview/interviewer/$inviteToken'
      preLoaderRoute: typeof HumanInterviewInterviewerInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$slug/chat/': {
      id: '/w/$slug/chat/'
      path: '/'
      fullPath: '/w/$slug/chat/'
      preLoaderRoute: typeof WSlugChatIndexRouteImport
      parentRoute: typeof WSlugChatRoute
    }
    '/w/$slug/studio/resumes': {
      id: '/w/$slug/studio/resumes'
      path: '/resumes'
      fullPath: '/w/$slug/studio/resumes'
      preLoaderRoute: typeof WSlugStudioResumesRouteImport
      parentRoute: typeof WSlugStudioRoute
    }
    '/w/$slug/studio/resume-pool': {
      id: '/w/$slug/studio/resume-pool'
      path: '/resume-pool'
      fullPath: '/w/$slug/studio/resume-pool'
      preLoaderRoute: typeof WSlugStudioResumePoolRouteImport
      parentRoute: typeof WSlugStudioRoute
    }
    '/w/$slug/studio/members': {
      id: '/w/$slug/studio/members'
      path: '/members'
      fullPath: '/w/$slug/studio/members'
      preLoaderRoute: typeof WSlugStudioMembersRouteImport
      parentRoute: typeof WSlugStudioRoute
    }
    '/w/$slug/studio/me': {
      id: '/w/$slug/studio/me'
      path: '/me'
      fullPath: '/w/$slug/studio/me'
      preLoaderRoute: typeof WSlugStudioMeRouteImport
      parentRoute: typeof WSlugStudioRoute
    }
    '/w/$slug/studio/mail-ingest-accounts': {
      id: '/w/$slug/studio/mail-ingest-accounts'
      path: '/mail-ingest-accounts'
      fullPath: '/w/$slug/studio/mail-ingest-accounts'
      preLoaderRoute: typeof WSlugStudioMailIngestAccountsRouteImport
      parentRoute: typeof WSlugStudioRoute
    }
    '/w/$slug/studio/job-descriptions': {
      id: '/w/$slug/studio/job-descriptions'
      path: '/job-descriptions'
      fullPath: '/w/$slug/studio/job-descriptions'
      preLoaderRoute: typeof WSlugStudioJobDescriptionsRouteImport
      parentRoute: typeof WSlugStudioRoute
    }
    '/w/$slug/studio/interviews': {
      id: '/w/$slug/studio/interviews'
      path: '/interviews'
      fullPath: '/w/$slug/studio/interviews'
      preLoaderRoute: typeof WSlugStudioInterviewsRouteImport
      parentRoute: typeof WSlugStudioRoute
    }
    '/w/$slug/studio/interviewers': {
      id: '/w/$slug/studio/interviewers'
      path: '/interviewers'
      fullPath: '/w/$slug/studio/interviewers'
      preLoaderRoute: typeof WSlugStudioInterviewersRouteImport
      parentRoute: typeof WSlugStudioRoute
    }
    '/w/$slug/studio/interview-questions': {
      id: '/w/$slug/studio/interview-questions'
      path: '/interview-questions'
      fullPath: '/w/$slug/studio/interview-questions'
      preLoaderRoute: typeof WSlugStudioInterviewQuestionsRouteImport
      parentRoute: typeof WSlugStudioRoute
    }
    '/w/$slug/studio/global-config': {
      id: '/w/$slug/studio/global-config'
      path: '/global-config'
      fullPath: '/w/$slug/studio/global-config'
      preLoaderRoute: typeof WSlugStudioGlobalConfigRouteImport
      parentRoute: typeof WSlugStudioRoute
    }
    '/w/$slug/studio/forms': {
      id: '/w/$slug/studio/forms'
      path: '/forms'
      fullPath: '/w/$slug/studio/forms'
      preLoaderRoute: typeof WSlugStudioFormsRouteImport
      parentRoute: typeof WSlugStudioRoute
    }
    '/w/$slug/studio/departments': {
      id: '/w/$slug/studio/departments'
      path: '/departments'
      fullPath: '/w/$slug/studio/departments'
      preLoaderRoute: typeof WSlugStudioDepartmentsRouteImport
      parentRoute: typeof WSlugStudioRoute
    }
    '/w/$slug/studio/dashboard': {
      id: '/w/$slug/studio/dashboard'
      path: '/dashboard'
      fullPath: '/w/$slug/studio/dashboard'
      preLoaderRoute: typeof WSlugStudioDashboardRouteImport
      parentRoute: typeof WSlugStudioRoute
    }
    '/w/$slug/chat/$sessionId': {
      id: '/w/$slug/chat/$sessionId'
      path: '/$sessionId'
      fullPath: '/w/$slug/chat/$sessionId'
      preLoaderRoute: typeof WSlugChatSessionIdRouteImport
      parentRoute: typeof WSlugChatRoute
    }
    '/w/$slug/studio/interviews/$roundId': {
      id: '/w/$slug/studio/interviews/$roundId'
      path: '/$roundId'
      fullPath: '/w/$slug/studio/interviews/$roundId'
      preLoaderRoute: typeof WSlugStudioInterviewsRoundIdRouteImport
      parentRoute: typeof WSlugStudioInterviewsRoute
    }
  }
}

interface InterviewIdRouteChildren {
  InterviewIdRoundIdRoute: typeof InterviewIdRoundIdRoute
}

const InterviewIdRouteChildren: InterviewIdRouteChildren = {
  InterviewIdRoundIdRoute: InterviewIdRoundIdRoute,
}

const InterviewIdRouteWithChildren = InterviewIdRoute._addFileChildren(
  InterviewIdRouteChildren,
)

interface InterviewRouteChildren {
  InterviewIdRoute: typeof InterviewIdRouteWithChildren
}

const InterviewRouteChildren: InterviewRouteChildren = {
  InterviewIdRoute: InterviewIdRouteWithChildren,
}

const InterviewRouteWithChildren = InterviewRoute._addFileChildren(
  InterviewRouteChildren,
)

interface PlatformRouteChildren {
  PlatformMailIngestAccountsRoute: typeof PlatformMailIngestAccountsRoute
  PlatformOrganizationsRoute: typeof PlatformOrganizationsRoute
  PlatformQueuesRoute: typeof PlatformQueuesRoute
  PlatformUsersRoute: typeof PlatformUsersRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformMailIngestAccountsRoute: PlatformMailIngestAccountsRoute,
  PlatformOrganizationsRoute: PlatformOrganizationsRoute,
  PlatformQueuesRoute: PlatformQueuesRoute,
  PlatformUsersRoute: PlatformUsersRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

interface WSlugChatRouteChildren {
  WSlugChatSessionIdRoute: typeof WSlugChatSessionIdRoute
  WSlugChatIndexRoute: typeof WSlugChatIndexRoute
}

const WSlugChatRouteChildren: WSlugChatRouteChildren = {
  WSlugChatSessionIdRoute: WSlugChatSessionIdRoute,
  WSlugChatIndexRoute: WSlugChatIndexRoute,
}

const WSlugChatRouteWithChildren = WSlugChatRoute._addFileChildren(
  WSlugChatRouteChildren,
)

interface WSlugStudioInterviewsRouteChildren {
  WSlugStudioInterviewsRoundIdRoute: typeof WSlugStudioInterviewsRoundIdRoute
}

const WSlugStudioInterviewsRouteChildren: WSlugStudioInterviewsRouteChildren = {
  WSlugStudioInterviewsRoundIdRoute: WSlugStudioInterviewsRoundIdRoute,
}

const WSlugStudioInterviewsRouteWithChildren =
  WSlugStudioInterviewsRoute._addFileChildren(
    WSlugStudioInterviewsRouteChildren,
  )

interface WSlugStudioRouteChildren {
  WSlugStudioDashboardRoute: typeof WSlugStudioDashboardRoute
  WSlugStudioDepartmentsRoute: typeof WSlugStudioDepartmentsRoute
  WSlugStudioFormsRoute: typeof WSlugStudioFormsRoute
  WSlugStudioGlobalConfigRoute: typeof WSlugStudioGlobalConfigRoute
  WSlugStudioInterviewQuestionsRoute: typeof WSlugStudioInterviewQuestionsRoute
  WSlugStudioInterviewersRoute: typeof WSlugStudioInterviewersRoute
  WSlugStudioInterviewsRoute: typeof WSlugStudioInterviewsRouteWithChildren
  WSlugStudioJobDescriptionsRoute: typeof WSlugStudioJobDescriptionsRoute
  WSlugStudioMailIngestAccountsRoute: typeof WSlugStudioMailIngestAccountsRoute
  WSlugStudioMeRoute: typeof WSlugStudioMeRoute
  WSlugStudioMembersRoute: typeof WSlugStudioMembersRoute
  WSlugStudioResumePoolRoute: typeof WSlugStudioResumePoolRoute
  WSlugStudioResumesRoute: typeof WSlugStudioResumesRoute
}

const WSlugStudioRouteChildren: WSlugStudioRouteChildren = {
  WSlugStudioDashboardRoute: WSlugStudioDashboardRoute,
  WSlugStudioDepartmentsRoute: WSlugStudioDepartmentsRoute,
  WSlugStudioFormsRoute: WSlugStudioFormsRoute,
  WSlugStudioGlobalConfigRoute: WSlugStudioGlobalConfigRoute,
  WSlugStudioInterviewQuestionsRoute: WSlugStudioInterviewQuestionsRoute,
  WSlugStudioInterviewersRoute: WSlugStudioInterviewersRoute,
  WSlugStudioInterviewsRoute: WSlugStudioInterviewsRouteWithChildren,
  WSlugStudioJobDescriptionsRoute: WSlugStudioJobDescriptionsRoute,
  WSlugStudioMailIngestAccountsRoute: WSlugStudioMailIngestAccountsRoute,
  WSlugStudioMeRoute: WSlugStudioMeRoute,
  WSlugStudioMembersRoute: WSlugStudioMembersRoute,
  WSlugStudioResumePoolRoute: WSlugStudioResumePoolRoute,
  WSlugStudioResumesRoute: WSlugStudioResumesRoute,
}

const WSlugStudioRouteWithChildren = WSlugStudioRoute._addFileChildren(
  WSlugStudioRouteChildren,
)

interface WSlugRouteChildren {
  WSlugChatRoute: typeof WSlugChatRouteWithChildren
  WSlugStudioRoute: typeof WSlugStudioRouteWithChildren
}

const WSlugRouteChildren: WSlugRouteChildren = {
  WSlugChatRoute: WSlugChatRouteWithChildren,
  WSlugStudioRoute: WSlugStudioRouteWithChildren,
}

const WSlugRouteWithChildren = WSlugRoute._addFileChildren(WSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  InterviewRoute: InterviewRouteWithChildren,
  LoginRoute: LoginRoute,
  PlatformRoute: PlatformRouteWithChildren,
  SelectWorkspaceRoute: SelectWorkspaceRoute,
  HumanInterviewInviteTokenRoute: HumanInterviewInviteTokenRoute,
  InviteTokenRoute: InviteTokenRoute,
  JoinCodeRoute: JoinCodeRoute,
  RRoundIdRoute: RRoundIdRoute,
  StudioInterviewsRoute: StudioInterviewsRoute,
  StudioResumePoolRoute: StudioResumePoolRoute,
  StudioResumesRoute: StudioResumesRoute,
  WSlugRoute: WSlugRouteWithChildren,
  HumanInterviewInterviewerInviteTokenRoute:
    HumanInterviewInterviewerInviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
